### ISSUE TITLE
Move Gettext.jl over at Julia-i18n organization.

### ISSUE THREAD

**Issue by Ismael-VC** [Julia-i18n/Gettext.jl#3]
Hello @garrison I'd like to request for this package to be transferred to  Julia-i18n organization:

* https://github.com/Julia-i18n/julia-i18n
* https://gitter.im/JuliaLangEs/julia-i18n
* https://www.transifex.com/projects/p/julialang-web

If you are fine with it of course, I'll be looking forward to your comments. Maybe this move will aid in maintaining this package and achieving https://github.com/garrison/Gettext.jl/issues/1.

**Comment by garrison** [comment]
Go for it! :smile:

**Comment by Ismael-VC** [comment]
Thank you very much for your support!

**Comment by Ismael-VC** [comment]
@garrison sorry to ping you again, but it seems that I need to have the **owner** role at this repo, in order to make the transfer. Only owners and not members are allowed to do this sort of administrative tasks and see the setting options for this repo, thanks in advance!

**Comment by waldyrious** [comment]
(otherwise, @garrison can transfer it himself in the repo settings page)

**Comment by garrison** [comment]
I [cannot add owners](http://stackoverflow.com/questions/8015579/add-another-user-to-project-owners-in-github) to a repository that is on my personal account.  I can transfer the ownership myself, but github is requiring me to be an admin of Julia-i18n.

**Comment by waldyrious** [comment]
Right, I had forgotten about that detail. I'll add you as an owner :)

**Comment by garrison** [comment]
Thanks! :smile:

Github transfer is done.  It would be nice to transfer the Travis admin rights (and link) as well, if that it possible...

**Comment by waldyrious** [comment]
@garrison I don't know if it is possible, but I believe you should have the appropriate permissions to do so if it is :) if you need any assistance, let us know (maybe @Ismael-VC can help more than I).

**Comment by Ismael-VC** [comment]
I'll see what needs to be done in order to have this fully operational, sorry for the late response, I've been somewhat busy, thank you both for your help!
